---
- hosts: localhost
  gather_facts: true

  tasks:
    - name: Set home folder
      set_fact:
        home: "{{ ansible_env.HOME }}"
        config: "{{ ansible_env.HOME }}/.config"
        dotfiles: "{{ ansible_env.HOME }}/dotfiles"
        brew: "/home/linuxbrew/.linuxbrew"

    - name: Install homebrew
      become: true
      shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Set permissions for homebrew
      become: true
      file:
        path: "{{ brew }}/.."
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        recurse: true

    - name: Add homebrew path
      lineinfile:
        path: "{{ home }}/.bashrc"
        create: true
        line: "{{ item }}"
      loop:
        - export "PATH={{ brew }}/bin:$PATH"
        - export "MANPATH={{ brew }}/share/man:$MANPATH"
        - export "INFOPATH={{ brew }}/share/info:$INFOPATH"

    - name: Install packages
      community.general.homebrew:
        name: 
          - git
          - gcc
          - node
          - neovim
          - fzf
          - htop
          - rsync
          - lsd
          - bat
          - ripgrep
          - tmux
          - zoxide
        update_homebrew: true 

    - name: Modify bashrc
      lineinfile:
        path: "{{ home }}/.bashrc"
        line: "{{ item }}"
      loop:
        - EDITOR=nvim
        - eval "$(fzf --bash)"

    - name: Create config dir if it does not exist
      file:
        path: "{{ config }}"
        state: directory

    - name: Get dotfile from GIT
      git:
        repo: https://github.com/AaySah92/config_dotfiles.git
        dest: "{{ dotfiles }}"

    - name: Register config files
      find:
        paths: "{{ dotfiles }}"
        file_type: any
      register: config_files

    - name: Create symlinks to config files
      file:
        dest: "{{ config }}/{{ item.path | basename }}"
        src: "{{ item.path }}"
        state: link
      loop: "{{ config_files.files }}"
