---
- hosts: localhost

  tasks:
    - name: Set home folder
      set_fact:
        home: "~/"
        brew: "/home/linuxbrew/.linuxbrew"

    - name: Install homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      become: true

    - name: Add homebrew path
      lineinfile:
        path: "{{ home }}/.bashrc"
        create: true
        line: "{{ item }}"
      loop:
        - export "PATH={{ brew }}/bin:$PATH"
        - export "MANPATH={{ brew }}/share/man:$MANPATH"
        - export "INFOPATH={{ brew }}/share/info:$INFOPATH"

    - name: Install packages
      community.general.homebrew:
        name: 
          - git
          - neovim
          - fzf
          - htop
          - rsync
          - lsd
          - bat
          - ripgrep
          - zoxide
        update_homebrew: true 

    - name: Modify bashrc
      lineinfile:
        path: "{{ home }}/.bashrc"
        line: "{{ item }}"
      loop:
        - EDITOR=nvim
        - eval "$(fzf --bash)"
